# argocd-rocketchat.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat
  namespace: argocd
spec:
  project: default
  sources:                                          # ✅ multiple sources
    - repoURL: https://rocketchat.github.io/helm-charts
      chart: rocketchat
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values-rocketchat.yaml
    - repoURL: https://github.com/klovekesh37/rocketchat-micro-argocd.git
      targetRevision: testing_iximiuz
      ref: values                                   # ✅ this is what $values points to
  destination:
    server: https://kubernetes.default.svc
    namespace: rc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
