# argocd-monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat-monitoring
  namespace: argocd
spec:
  project: default
  sources:                                          
    - repoURL: https://rocketchat.github.io/helm-charts
      chart: monitoring
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values-monitoring.yaml
    - repoURL: https://github.com/klovekesh37/rocketchat-micro-argocd.git
      targetRevision: testing_iximiuz
      ref: values                                   
  destination:
    server: https://kubernetes.default.svc
    namespace: rc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
