---
apiVersion: v1
kind: Secret
metadata:
  namespace: rc
  name:  mongodb-admin-password
type: Opaque
stringData:
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  namespace: rc
  name: mongodb-rocketchat-password
type:  Opaque
stringData:
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  namespace: rc
  name: metrics-endpoint-password
type:  Opaque
stringData:
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  namespace: rc
  name: admin-scram-credentials
type:  Opaque
stringData: 
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  namespace: rc
  name: rocketchat-scram-credentials
type: Opaque
stringData:
  username: rocketchat
  password: admin
